### PR TITLE
Fix utf-8 base64 decode problem

### PR DESCRIPTION
**Pull request by rzkhrv**

### CODE REVIEW

**Review by adityatelange — COMMENTED** [review]
Which utf-8 base64 decode problem?

**Comment by rzkhrv** [comment]
Hi. In my case, this is decoding Cyrillic characters, but you can read about the problem [here](https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings).

**Comment by rzkhrv** [comment]
For example, this is in your version https://ibb.co/z6x0yHb and this in my version https://ibb.co/vqTPvL3.

**Comment by adityatelange** [comment]
> Hi. In my case, this is decoding Cyrillic characters, but you can read about the problem [here](https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings).

Got it, thanks! I didn't notice this was happening.

**Review by adityatelange — APPROVED** [review]

**Pull request merged**
